name: Test Orca Secrets action

on: [pull_request, workflow_dispatch]

jobs:
  secrets_scan_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Scan Secrets
        id: orcasecurity
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          console_output: "table"
