name: Test Orca Secrets action

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  secrets_scan_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan Secrets
        id: orcasecurity
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          console_output: "table"

