name: Test Orca Secrets action

on: [push, pull_request, workflow_dispatch]

jobs:
  secrets_scan_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan Secrets
        id: orcasecurity
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          console_output: "table"