name: Test Orca Secrets action - Sarif

on: [pull_request, workflow_dispatch]

jobs:
  secrets_scan_job:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Scan Secrets
        id: orcasecurity_secrets_scan
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          format: "sarif"
          output: "results/"
          console_output: "table"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # ratchet:github/codeql-action/upload-sarif@v3.27.5
        if: ${{ always() && steps.orcasecurity_secrets_scan.outputs.exit_code != 1 }}
        with:
          sarif_file: results/secrets.sarif
