name: Test Orca Secrets action - Sarif

on: [push, pull_request]

jobs:
  secrets_scan_job:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan Secrets
        id: orcasecurity_secrets_scan
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          format: "sarif"
          output: "results/"
          console_output: "table"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # ratchet:github/codeql-action/upload-sarif@v3
        if: ${{ always() && steps.orcasecurity_secrets_scan.outputs.exit_code != 1 }}
        with:
          sarif_file: results/secrets.sarif# TODO: Need to fix the workflow
